### ISSUE TITLE
How can i disable the otp without remove otp middleware from routes?

### ISSUE THREAD

**Issue by jazz7381** [erdemkeren/laravel-otp#15]
is it possible to disable the otp without remove middleware from routes? it will good if there is option to disable it when in development, you can make it as an option in otp.php config file perhaps

**Comment by erdemkeren** [comment]
Extending `\Erdemkeren\Otp\Http\Middleware\Otp` class and checking the config file for such flag and then using it as your route middleware should work.

For example:

```php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class Otp extends \Erdemkeren\Otp\Http\Middleware\Otp
{
    public function handle(Request $request, Closure $next, $guard = null)
    {
        if(config('app.name') === 'dev') {
            return $next($request);
        }

        return parent::handle($request, $next, $guard);
    }
}
```

```php
protected $routeMiddleware = [
    // [...]
    'otp' => \App\Http\Middleware\Otp::class,
];
```
