### ISSUE TITLE
Problem pushing notification to queue

### ISSUE THREAD

**Issue by ngugijames** [erdemkeren/laravel-otp#5]
Hey, 

I have installed the latest version of this package. My composer reads:
"erdemkeren/laravel-otp": "^1.0",
"laravel/framework": "5.5.*",

When this package tries to push the TokenNotification to a queue, I get the following error:

**serialize(): &quot;macros&quot; returned as member variable from __sleep() but does not exist**

It seems the macros property in the Macroable trait is not serialized properly.

**Comment by ngugijames** [comment]
I can confirm this issue no longer exists.

**Comment by ngugijames** [comment]
Spoke too soon. This is still an issue.
The Macroable trait in the Notification class is the culprit. https://github.com/erdemkeren/laravel-otp/blob/e9956b99288f527ad678cd0b5e4c815c6cfc1b66/src/TokenNotification.php#L21

**Comment by erdemkeren** [comment]
Hey, on it.

**Comment by erdemkeren** [comment]
Hello, @ngugijames;

I tried to reproduce this issue on v3. However, I couldn't. Can you please validate?

Here is my setup:

Queue Driver: database
laravel-otp version: v3
laravel version: 7

AppServiceProvider.php@register:

```php
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        TokenNotification::macro('toConsole', function () {
            return $this->token->plainText();
        });
    }
```

`ConsoleChannel`:

```php
<?php

namespace App\Channels;

use Illuminate\Notifications\Notification;

class ConsoleChannel
{
    /**
     * Send the given notification.
     *
     * @param  mixed  $notifiable
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return void
     */
    public function send($notifiable, Notification $notification)
    {
        $message = $notification->toConsole($notifiable);

        var_dump($message);
    }
}
```

User:

```php
class User extends Authenticatable
{
    use Notifiable;

    public function otpChannels(): array
    {
        return [ConsoleChannel::class];
    }
}
```

When I run `art queue:work`

I see:

```
[2020-05-31 12:19:18][6] Processing: Erdemkeren\Otp\TokenNotification
string(6) "IPVjk6"
[2020-05-31 12:19:18][6] Processed:  Erdemkeren\Otp\TokenNotification
```

**Comment by erdemkeren** [comment]
I couldn't reproduce the problem. Please feel free to open if required.
